'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
let W=0,H=0,DPR=1,last=performance.now(),score=0,gameOver=false,time=0;
const keys=new Set();
const world={w:1800,h:1100,walls:[{x:0,y:0,w:1800,h:40},{x:0,y:1060,w:1800,h:40},{x:0,y:0,w:40,h:1100},{x:1760,y:0,w:40,h:1100},{x:360,y:180,w:420,h:48},{x:1000,y:160,w:48,h:420},{x:520,y:560,w:560,h:48},{x:1280,y:500,w:300,h:48},{x:260,y:820,w:420,h:48}]};
const player={x:260,y:300,r:20,speed:230,hp:100,maxHp:100,dirX:1,dirY:0,attackCd:0,color:'#d8b45a',role:'Guardian'};
const allies=[
{x:215,y:345,r:17,speed:190,hp:75,maxHp:75,color:'#d8b45a',role:'Warden',range:70,cd:0,dirX:1,dirY:0},
{x:205,y:260,r:16,speed:205,hp:60,maxHp:60,color:'#4f8e5a',role:'Ranger',range:250,cd:0,dirX:1,dirY:0},
{x:260,y:350,r:16,speed:185,hp:55,maxHp:55,color:'#496fa8',role:'Arcanist',range:220,cd:0,dirX:1,dirY:0}
];
const enemies=[],projectiles=[],slashes=[],pickups=[],particles=[];
const spawners=[{x:1450,y:250,hp:120,t:0},{x:1480,y:850,hp:120,t:0},{x:780,y:900,hp:120,t:0}];
const torches=[{x:180,y:170},{x:870,y:150},{x:1150,y:620},{x:1620,y:390},{x:450,y:950},{x:1120,y:950}];
const joystick={active:false,id:null,baseX:115,baseY:0,x:0,y:0,dx:0,dy:0};const attack={active:false,id:null};
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0);joystick.baseY=H-105}
addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.code==='Space')doAttack(player)});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);if(e.clientX<W*.5&&!joystick.active){joystick.active=true;joystick.id=e.pointerId;joystick.baseX=e.clientX;joystick.baseY=e.clientY;joystick.x=e.clientX;joystick.y=e.clientY}else if(!attack.active){attack.active=true;attack.id=e.pointerId;doAttack(player)}});
canvas.addEventListener('pointermove',e=>{if(e.pointerId===joystick.id){joystick.x=e.clientX;joystick.y=e.clientY;let dx=e.clientX-joystick.baseX,dy=e.clientY-joystick.baseY,m=Math.hypot(dx,dy),lim=48;if(m>lim){dx*=lim/m;dy*=lim/m}joystick.dx=dx/lim;joystick.dy=dy/lim}});
function release(e){if(e.pointerId===joystick.id){joystick.active=false;joystick.id=null;joystick.dx=joystick.dy=0}if(e.pointerId===attack.id){attack.active=false;attack.id=null}}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
function circleRect(o,r){let nx=Math.max(r.x,Math.min(o.x,r.x+r.w)),ny=Math.max(r.y,Math.min(o.y,r.y+r.h));return(o.x-nx)**2+(o.y-ny)**2<o.r**2}
function move(o,vx,vy,dt){o.x+=vx*dt;for(const r of world.walls)if(circleRect(o,r))o.x-=vx*dt;o.y+=vy*dt;for(const r of world.walls)if(circleRect(o,r))o.y-=vy*dt;o.x=Math.max(o.r,Math.min(world.w-o.r,o.x));o.y=Math.max(o.r,Math.min(world.h-o.r,o.y))}
function nearest(from,list,filter=()=>true){let best=null,bd=1e9;for(const o of list)if(filter(o)){let d=(o.x-from.x)**2+(o.y-from.y)**2;if(d<bd){bd=d;best=o}}return best}
function burst(x,y,color,n=8){for(let i=0;i<n;i++){let a=Math.random()*7,s=30+Math.random()*100;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.35,max:.6,color,size:2+Math.random()*3})}}
function doAttack(a){if(a.attackCd>0||gameOver)return;a.attackCd=.38;slashes.push({x:a.x,y:a.y,dx:a.dirX,dy:a.dirY,t:.18});for(const e of enemies){let dx=e.x-a.x,dy=e.y-a.y,d=Math.hypot(dx,dy),dot=(dx*a.dirX+dy*a.dirY)/(d||1);if(d<92&&dot>.1){e.hp-=34;e.vx+=a.dirX*120;e.vy+=a.dirY*120;burst(e.x,e.y,'#d74b35',7)}}}
function shoot(a,target,damage=17,speed=420){let dx=target.x-a.x,dy=target.y-a.y,m=Math.hypot(dx,dy)||1;projectiles.push({x:a.x,y:a.y,vx:dx/m*speed,vy:dy/m*speed,r:5,damage,life:1.4,color:a.color,role:a.role})}
function spawnEnemy(s){enemies.push({x:s.x+(Math.random()-.5)*55,y:s.y+(Math.random()-.5)*55,r:15,speed:85+Math.random()*35,hp:45,maxHp:45,vx:0,vy:0,hit:0,type:Math.random()<.7?'skeleton':'ghoul'})}
function update(dt){time+=dt;if(gameOver)return;player.attackCd=Math.max(0,player.attackCd-dt);let mx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joystick.dx,my=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+joystick.dy,m=Math.hypot(mx,my);if(m>1){mx/=m;my/=m}if(m>.08){player.dirX=mx;player.dirY=my}move(player,mx*player.speed,my*player.speed,dt);if(attack.active&&player.attackCd<=0)doAttack(player);
for(const a of allies){a.cd=Math.max(0,a.cd-dt);let target=nearest(a,enemies,e=>e.hp>0),dx=player.x-a.x,dy=player.y-a.y,d=Math.hypot(dx,dy);if(target&&Math.hypot(target.x-a.x,target.y-a.y)<a.range){let tx=target.x-a.x,ty=target.y-a.y,tm=Math.hypot(tx,ty)||1;a.dirX=tx/tm;a.dirY=ty/tm;if(a.cd<=0){if(a.role==='Warden'){target.hp-=22;burst(target.x,target.y,'#e6c66b',4);a.cd=.55}else{shoot(a,target,a.role==='Arcanist'?24:17,a.role==='Arcanist'?340:460);a.cd=a.role==='Arcanist'?.9:.58}}if(d>260)move(a,dx/d*a.speed,dy/d*a.speed,dt)}else if(d>70)move(a,dx/(d||1)*a.speed,dy/(d||1)*a.speed,dt)}
for(const s of spawners){if(s.hp<=0)continue;s.t-=dt;if(s.t<=0){spawnEnemy(s);s.t=1.3+Math.random()*.7}}
for(const e of enemies){e.hit=Math.max(0,e.hit-dt);let targets=[player,...allies].filter(x=>x.hp>0),t=nearest(e,targets);if(!t)continue;let dx=t.x-e.x,dy=t.y-e.y,d=Math.hypot(dx,dy)||1;e.vx*=.88;e.vy*=.88;move(e,dx/d*e.speed+e.vx,dy/d*e.speed+e.vy,dt);if(d<t.r+e.r+4&&e.hit<=0){t.hp-=8;e.hit=.75;burst(t.x,t.y,'#a63030',5);if(t===player&&t.hp<=0)gameOver=true}}
for(const p of projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;particles.push({x:p.x,y:p.y,vx:0,vy:0,life:.12,max:.12,color:p.role==='Arcanist'?'#74a9ff':'#c8d59b',size:3});for(const e of enemies)if(e.hp>0&&Math.hypot(e.x-p.x,e.y-p.y)<e.r+p.r){e.hp-=p.damage;p.life=0;burst(e.x,e.y,p.role==='Arcanist'?'#74a9ff':'#d7b866',7);break}for(const s of spawners)if(s.hp>0&&Math.hypot(s.x-p.x,s.y-p.y)<27+p.r){s.hp-=p.damage;p.life=0;break}}
for(const e of enemies)if(e.hp<=0&&!e.dead){e.dead=true;score+=25;burst(e.x,e.y,'#6b1717',12);if(Math.random()<.12)pickups.push({x:e.x,y:e.y,r:11,type:'food'})}
for(const p of pickups)if(Math.hypot(player.x-p.x,player.y-p.y)<player.r+p.r){player.hp=Math.min(player.maxHp,player.hp+20);p.dead=true;score+=10;burst(p.x,p.y,'#7bdc78',10)}for(const s of spawners)if(s.hp<=0&&!s.dead){s.dead=true;score+=150;burst(s.x,s.y,'#a96cff',22)}
enemies.splice(0,enemies.length,...enemies.filter(e=>e.hp>0));projectiles.splice(0,projectiles.length,...projectiles.filter(p=>p.life>0));pickups.splice(0,pickups.length,...pickups.filter(p=>!p.dead));slashes.forEach(s=>s.t-=dt);slashes.splice(0,slashes.length,...slashes.filter(s=>s.t>0));for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;p.vx*=.94;p.vy*=.94}particles.splice(0,particles.length,...particles.filter(p=>p.life>0))}
function bar(x,y,w,h,v,max,color){ctx.fillStyle='#17110d';ctx.fillRect(x,y,w,h);ctx.fillStyle=color;ctx.fillRect(x,y,w*Math.max(0,v/max),h);ctx.strokeStyle='#b8934d';ctx.strokeRect(x+.5,y+.5,w-1,h-1)}
function floorTile(x,y,s){let v=((x/s+y/s)&1)?'#292722':'#25231f';ctx.fillStyle=v;ctx.fillRect(x,y,s,s);ctx.strokeStyle='#11100e';ctx.strokeRect(x+.5,y+.5,s-1,s-1);ctx.strokeStyle='#39352e';ctx.beginPath();ctx.moveTo(x+6,y+s-7);ctx.lineTo(x+s*.48,y+s*.42);ctx.lineTo(x+s-8,y+9);ctx.stroke()}
function drawWall(r){ctx.fillStyle='#11100f';ctx.fillRect(r.x+8,r.y+10,r.w,r.h);ctx.fillStyle='#3b3933';ctx.fillRect(r.x,r.y,r.w,r.h);for(let yy=r.y;yy<r.y+r.h;yy+=18)for(let xx=r.x;xx<r.x+r.w;xx+=36){ctx.fillStyle=((xx+yy)/18)%2?'#45423b':'#34322d';ctx.fillRect(xx,yy,34,16);ctx.strokeStyle='#1b1a18';ctx.strokeRect(xx+.5,yy+.5,34,16)}ctx.strokeStyle='#7c6543';ctx.strokeRect(r.x+.5,r.y+.5,r.w-1,r.h-1)}
function shadow(x,y,rx,ry){ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(x+5,y+9,rx,ry,0,0,7);ctx.fill()}
function drawHero(a,isPlayer=false){let ang=Math.atan2(a.dirY||0,a.dirX||1);shadow(a.x,a.y,a.r*.9,a.r*.42);ctx.save();ctx.translate(a.x,a.y);ctx.rotate(ang+Math.PI/2);if(a.role==='Ranger'){ctx.fillStyle='#274b31';ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(-15,18);ctx.lineTo(15,18);ctx.closePath();ctx.fill();ctx.fillStyle='#6a4d2c';ctx.fillRect(-3,-4,6,25);ctx.strokeStyle='#d7c17a';ctx.beginPath();ctx.arc(9,2,13,-1.2,1.2);ctx.stroke()}else if(a.role==='Arcanist'){ctx.fillStyle='#27446f';ctx.beginPath();ctx.moveTo(0,-23);ctx.lineTo(-16,18);ctx.lineTo(16,18);ctx.closePath();ctx.fill();ctx.fillStyle='#d7d2c4';ctx.beginPath();ctx.arc(0,-8,7,0,7);ctx.fill();ctx.strokeStyle='#76a7ff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(10,-13);ctx.lineTo(10,18);ctx.stroke()}else{ctx.fillStyle=isPlayer?'#253956':'#d8d0b5';ctx.beginPath();ctx.moveTo(0,-23);ctx.lineTo(-17,16);ctx.lineTo(17,16);ctx.closePath();ctx.fill();ctx.fillStyle='#82745a';ctx.fillRect(-11,-12,22,22);ctx.fillStyle='#c7c3b6';ctx.beginPath();ctx.arc(0,-12,10,0,7);ctx.fill();ctx.strokeStyle='#e7d48c';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(5,-6);ctx.lineTo(19,13);ctx.stroke()}ctx.restore();bar(a.x-20,a.y-a.r-16,40,5,a.hp,a.maxHp,isPlayer?'#b62920':'#4f9a4f')}
function drawEnemy(e){shadow(e.x,e.y,14,6);ctx.save();ctx.translate(e.x,e.y);if(e.type==='skeleton'){ctx.strokeStyle='#ddd3b8';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(0,10);ctx.moveTo(-10,0);ctx.lineTo(10,0);ctx.moveTo(0,10);ctx.lineTo(-8,19);ctx.moveTo(0,10);ctx.lineTo(8,19);ctx.stroke();ctx.fillStyle='#e2d6bd';ctx.beginPath();ctx.arc(0,-13,8,0,7);ctx.fill();ctx.fillStyle='#27120e';ctx.fillRect(-4,-15,3,3);ctx.fillRect(2,-15,3,3)}else{ctx.fillStyle='#675342';ctx.beginPath();ctx.arc(0,0,16,0,7);ctx.fill();ctx.fillStyle='#92765a';ctx.beginPath();ctx.arc(0,-13,9,0,7);ctx.fill();ctx.fillStyle='#e75a3c';ctx.fillRect(-5,-15,3,3);ctx.fillRect(2,-15,3,3)}ctx.restore();bar(e.x-16,e.y-28,32,4,e.hp,e.maxHp,'#b62920')}
function drawSpawner(s){let pulse=1+Math.sin(time*5)*.08;ctx.save();ctx.translate(s.x,s.y);ctx.scale(pulse,pulse);let g=ctx.createRadialGradient(0,0,4,0,0,48);g.addColorStop(0,'#f2a7ff');g.addColorStop(.35,'#8d36bd');g.addColorStop(1,'#2b0b3800');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,48,0,7);ctx.fill();ctx.strokeStyle='#c47cff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,26,time,time+5);ctx.stroke();for(let i=0;i<4;i++){let a=time+i*Math.PI/2;ctx.fillStyle='#6d497a';ctx.fillRect(Math.cos(a)*25-5,Math.sin(a)*25-5,10,10)}ctx.restore();bar(s.x-25,s.y-40,50,5,s.hp,120,'#9c4db5')}
function drawTorch(t){let flick=Math.sin(time*12+t.x)*3;let g=ctx.createRadialGradient(t.x,t.y,2,t.x,t.y,85+flick);g.addColorStop(0,'#ffd56a88');g.addColorStop(.4,'#f08d2938');g.addColorStop(1,'#0000');ctx.fillStyle=g;ctx.beginPath();ctx.arc(t.x,t.y,90,0,7);ctx.fill();ctx.fillStyle='#67462d';ctx.fillRect(t.x-3,t.y,6,18);ctx.fillStyle='#ffb234';ctx.beginPath();ctx.moveTo(t.x,t.y-14-flick);ctx.quadraticCurveTo(t.x-9,t.y-3,t.x,t.y+2);ctx.quadraticCurveTo(t.x+9,t.y-3,t.x,t.y-14-flick);ctx.fill()}
function draw(){ctx.clearRect(0,0,W,H);const camX=Math.max(0,Math.min(world.w-W,player.x-W/2)),camY=Math.max(0,Math.min(world.h-H,player.y-H/2));ctx.save();ctx.translate(-camX,-camY);ctx.fillStyle='#171612';ctx.fillRect(0,0,world.w,world.h);for(let y=0;y<world.h;y+=64)for(let x=0;x<world.w;x+=64)floorTile(x,y,64);ctx.fillStyle='#1118';for(let i=0;i<60;i++){let x=(i*193)%world.w,y=(i*347)%world.h;ctx.beginPath();ctx.arc(x,y,2+(i%4),0,7);ctx.fill()}world.walls.forEach(drawWall);torches.forEach(drawTorch);for(const s of spawners)if(s.hp>0)drawSpawner(s);for(const p of pickups){shadow(p.x,p.y,10,4);ctx.fillStyle='#8f2c22';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();ctx.fillStyle='#e5c37d';ctx.fillRect(p.x-2,p.y-8,4,15)}for(const p of projectiles){ctx.shadowBlur=14;ctx.shadowColor=p.role==='Arcanist'?'#6da4ff':'#e8d68c';ctx.fillStyle=p.role==='Arcanist'?'#93b9ff':'#e8d68c';ctx.beginPath();ctx.arc(p.x,p.y,p.r+2,0,7);ctx.fill();ctx.shadowBlur=0}for(const e of enemies)drawEnemy(e);for(const a of allies)drawHero(a,false);drawHero(player,true);for(const s of slashes){let ang=Math.atan2(s.dy,s.dx);ctx.strokeStyle='#ffd88a';ctx.lineWidth=10;ctx.shadowBlur=16;ctx.shadowColor='#f6a63d';ctx.beginPath();ctx.arc(s.x,s.y,48,ang-.75,ang+.75);ctx.stroke();ctx.shadowBlur=0}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,7);ctx.fill()}ctx.globalAlpha=1;ctx.restore();let vg=ctx.createRadialGradient(W/2,H/2,Math.min(W,H)*.25,W/2,H/2,Math.max(W,H)*.7);vg.addColorStop(0,'#0000');vg.addColorStop(1,'#0009');ctx.fillStyle=vg;ctx.fillRect(0,0,W,H);if(gameOver){ctx.fillStyle='#090705dd';ctx.fillRect(0,0,W,H);ctx.fillStyle='#e5d5a6';ctx.textAlign='center';ctx.font='bold 42px Georgia';ctx.fillText('YOU HAVE FALLEN',W/2,H/2-15);ctx.font='20px Georgia';ctx.fillText('Refresh to begin another run',W/2,H/2+28);ctx.textAlign='left'}}
function loop(now){let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
