'use strict';
const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d');
const soundGate=document.getElementById('soundGate');
let W=innerWidth,H=innerHeight,last=performance.now(),time=0,score=0,gameOver=false;
const keys=new Set();
const world={w:1800,h:1100,walls:[{x:0,y:0,w:1800,h:40},{x:0,y:1060,w:1800,h:40},{x:0,y:0,w:40,h:1100},{x:1760,y:0,w:40,h:1100},{x:360,y:180,w:420,h:48},{x:1000,y:160,w:48,h:420},{x:520,y:560,w:560,h:48},{x:1280,y:500,w:300,h:48},{x:260,y:820,w:420,h:48}]};
const player={x:260,y:300,r:20,speed:230,hp:100,maxHp:100,dirX:1,dirY:0,attackCd:0,attackT:0,walk:0,role:'Guardian'};
const allies=[
{x:215,y:345,r:18,speed:190,hp:75,maxHp:75,role:'Warden',range:78,cd:0,attackT:0,dirX:1,dirY:0,walk:1.4},
{x:205,y:260,r:17,speed:205,hp:60,maxHp:60,role:'Ranger',range:280,cd:0,attackT:0,dirX:1,dirY:0,walk:3.1},
{x:260,y:350,r:17,speed:185,hp:55,maxHp:55,role:'Arcanist',range:245,cd:0,attackT:0,dirX:1,dirY:0,walk:4.8}
];
const enemies=[],projectiles=[],pickups=[],particles=[],slashes=[];
const spawners=[{x:1450,y:250,hp:150,t:0},{x:1480,y:850,hp:150,t:0},{x:780,y:900,hp:150,t:0}];
const torches=[{x:180,y:170},{x:870,y:150},{x:1150,y:620},{x:1620,y:390},{x:450,y:950},{x:1120,y:950}];
const joystick={active:false,id:null,baseX:110,baseY:H-100,dx:0,dy:0};
const attack={active:false,id:null};

function resize(){W=innerWidth;H=innerHeight;canvas.width=W;canvas.height=H;canvas.style.width=W+'px';canvas.style.height=H+'px';joystick.baseY=H-100}
addEventListener('resize',resize);resize();

let audioCtx=null,master=null;
function enableAudio(){
  if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=.22;master.connect(audioCtx.destination)}
  if(audioCtx.state==='suspended')audioCtx.resume();
  soundGate.classList.add('hidden');
  tone(520,.06,'sine',.12,680);
}
function tone(freq,dur,type='sine',gain=.1,endFreq=freq){if(!audioCtx||audioCtx.state!=='running')return;const now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(40,endFreq),now+dur);g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.001,now+dur);o.connect(g);g.connect(master);o.start(now);o.stop(now+dur)}
function noise(dur=.08,gain=.08){if(!audioCtx||audioCtx.state!=='running')return;const sr=audioCtx.sampleRate,b=audioCtx.createBuffer(1,Math.floor(sr*dur),sr),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const s=audioCtx.createBufferSource(),g=audioCtx.createGain();s.buffer=b;g.gain.value=gain;s.connect(g);g.connect(master);s.start()}
const sfx={sword(){tone(310,.09,'sawtooth',.08,110);noise(.06,.055)},hit(){tone(95,.07,'square',.08,55);noise(.05,.07)},arrow(){tone(760,.06,'triangle',.05,340)},magic(){tone(280,.18,'sine',.07,820);tone(560,.15,'triangle',.04,1200)},hammer(){tone(125,.13,'square',.09,62);noise(.11,.08)},enemy(){tone(180,.08,'sawtooth',.05,90)}};
soundGate.addEventListener('pointerdown',e=>{e.stopPropagation();enableAudio()});

addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.code==='Space')doAttack(player)});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
canvas.addEventListener('pointerdown',e=>{enableAudio();canvas.setPointerCapture(e.pointerId);if(e.clientX<W*.52&&!joystick.active){joystick.active=true;joystick.id=e.pointerId;joystick.baseX=e.clientX;joystick.baseY=e.clientY}else if(!attack.active){attack.active=true;attack.id=e.pointerId;doAttack(player)}});
canvas.addEventListener('pointermove',e=>{if(e.pointerId!==joystick.id)return;let dx=e.clientX-joystick.baseX,dy=e.clientY-joystick.baseY,m=Math.hypot(dx,dy),lim=52;if(m>lim){dx*=lim/m;dy*=lim/m}joystick.dx=dx/lim;joystick.dy=dy/lim});
function release(e){if(e.pointerId===joystick.id){joystick.active=false;joystick.id=null;joystick.dx=joystick.dy=0}if(e.pointerId===attack.id){attack.active=false;attack.id=null}}
canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);

function circleRect(o,r){const nx=Math.max(r.x,Math.min(o.x,r.x+r.w)),ny=Math.max(r.y,Math.min(o.y,r.y+r.h));return(o.x-nx)**2+(o.y-ny)**2<o.r**2}
function move(o,vx,vy,dt){o.x+=vx*dt;for(const r of world.walls)if(circleRect(o,r))o.x-=vx*dt;o.y+=vy*dt;for(const r of world.walls)if(circleRect(o,r))o.y-=vy*dt;o.x=Math.max(o.r,Math.min(world.w-o.r,o.x));o.y=Math.max(o.r,Math.min(world.h-o.r,o.y));if(Math.hypot(vx,vy)>10)o.walk+=dt*9}
function nearest(from,list,filter=()=>true){let best=null,bd=Infinity;for(const o of list)if(filter(o)){const d=(o.x-from.x)**2+(o.y-from.y)**2;if(d<bd){bd=d;best=o}}return best}
function burst(x,y,color,n=8){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=35+Math.random()*120;particles.push({x,y,z:8,vx:Math.cos(a)*v,vy:Math.sin(a)*v,vz:40+Math.random()*80,life:.25+Math.random()*.35,max:.6,color,size:2+Math.random()*3})}}
function doAttack(a){if(a.attackCd>0||gameOver)return;a.attackCd=.42;a.attackT=.28;sfx.sword();slashes.push({x:a.x,y:a.y,dx:a.dirX,dy:a.dirY,t:.22});for(const e of enemies){const dx=e.x-a.x,dy=e.y-a.y,d=Math.hypot(dx,dy)||1,dot=(dx*a.dirX+dy*a.dirY)/d;if(d<102&&dot>-.05){e.hp-=36;e.flash=.12;e.vx+=a.dirX*150;e.vy+=a.dirY*150;burst(e.x,e.y,'#c54132',10);sfx.hit()}}}
function shoot(a,target,damage=17,speed=430){const dx=target.x-a.x,dy=target.y-a.y,m=Math.hypot(dx,dy)||1;projectiles.push({x:a.x,y:a.y,z:25,vx:dx/m*speed,vy:dy/m*speed,r:5,damage,life:1.4,role:a.role});a.attackT=.22;if(a.role==='Arcanist')sfx.magic();else sfx.arrow()}
function spawnEnemy(s){const r=Math.random(),type=r<.5?'skeleton':r<.75?'goblin':r<.93?'ghoul':'brute',st={skeleton:[16,92,52],goblin:[15,126,38],ghoul:[19,98,68],brute:[27,62,145]}[type];enemies.push({x:s.x+(Math.random()-.5)*55,y:s.y+(Math.random()-.5)*55,r:st[0],speed:st[1],hp:st[2],maxHp:st[2],vx:0,vy:0,hit:0,flash:0,attackT:0,walk:Math.random()*6,type,dirX:1,dirY:0})}

function update(dt){
 time+=dt;if(gameOver)return;
 player.attackCd=Math.max(0,player.attackCd-dt);player.attackT=Math.max(0,player.attackT-dt);
 let mx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+joystick.dx;
 let my=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+joystick.dy;
 let m=Math.hypot(mx,my);if(m>1){mx/=m;my/=m}if(m>.08){player.dirX=mx;player.dirY=my}move(player,mx*player.speed,my*player.speed,dt);if(attack.active&&player.attackCd<=0)doAttack(player);
 for(const a of allies){a.cd=Math.max(0,a.cd-dt);a.attackT=Math.max(0,a.attackT-dt);const target=nearest(a,enemies,e=>e.hp>0),dx=player.x-a.x,dy=player.y-a.y,d=Math.hypot(dx,dy)||1;if(target&&Math.hypot(target.x-a.x,target.y-a.y)<a.range){const tx=target.x-a.x,ty=target.y-a.y,tm=Math.hypot(tx,ty)||1;a.dirX=tx/tm;a.dirY=ty/tm;if(a.cd<=0){if(a.role==='Warden'){target.hp-=24;target.flash=.1;a.attackT=.28;a.cd=.62;sfx.hammer();burst(target.x,target.y,'#f1cc67',6)}else{shoot(a,target,a.role==='Arcanist'?26:18,a.role==='Arcanist'?350:480);a.cd=a.role==='Arcanist'?.92:.62}}}else if(d>78)move(a,dx/d*a.speed,dy/d*a.speed,dt)}
 for(const s of spawners){if(s.hp<=0)continue;s.t-=dt;if(s.t<=0){spawnEnemy(s);s.t=1.3+Math.random()*.75}}
 for(const e of enemies){e.hit=Math.max(0,e.hit-dt);e.flash=Math.max(0,e.flash-dt);e.attackT=Math.max(0,e.attackT-dt);const t=nearest(e,[player,...allies].filter(q=>q.hp>0));if(!t)continue;const dx=t.x-e.x,dy=t.y-e.y,d=Math.hypot(dx,dy)||1;e.dirX=dx/d;e.dirY=dy/d;e.vx*=.88;e.vy*=.88;move(e,e.dirX*e.speed+e.vx,e.dirY*e.speed+e.vy,dt);if(d<t.r+e.r+5&&e.hit<=0){t.hp-=e.type==='brute'?16:8;e.hit=e.type==='goblin'?.48:.75;e.attackT=.26;sfx.enemy();burst(t.x,t.y,'#a62e27',6);if(t===player&&t.hp<=0)gameOver=true}}
 for(const p of projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;particles.push({x:p.x,y:p.y,z:p.z,vx:0,vy:0,vz:0,life:.12,max:.12,color:p.role==='Arcanist'?'#8daeff':'#e5d487',size:3});for(const e of enemies)if(e.hp>0&&Math.hypot(e.x-p.x,e.y-p.y)<e.r+p.r){e.hp-=p.damage;e.flash=.1;p.life=0;burst(e.x,e.y,p.role==='Arcanist'?'#7f9cff':'#d8c169',8);sfx.hit();break}}
 for(const e of enemies)if(e.hp<=0&&!e.dead){e.dead=true;score+=e.type==='brute'?85:25;burst(e.x,e.y,'#6b1e19',14);if(Math.random()<.13)pickups.push({x:e.x,y:e.y,r:11})}
 for(const p of pickups)if(Math.hypot(player.x-p.x,player.y-p.y)<player.r+p.r){player.hp=Math.min(player.maxHp,player.hp+20);p.dead=true;score+=10;burst(p.x,p.y,'#78d276',10)}
 enemies.splice(0,enemies.length,...enemies.filter(e=>e.hp>0));projectiles.splice(0,projectiles.length,...projectiles.filter(p=>p.life>0));pickups.splice(0,pickups.length,...pickups.filter(p=>!p.dead));slashes.forEach(s=>s.t-=dt);slashes.splice(0,slashes.length,...slashes.filter(s=>s.t>0));
 for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vz-=180*dt;p.life-=dt;p.vx*=.94;p.vy*=.94}particles.splice(0,particles.length,...particles.filter(p=>p.life>0))
}

function project(wx,wy,z=0){const dx=wx-player.x,dy=wy-player.y;return{x:W*.5+(dx-dy)*.66,y:H*.51+(dx+dy)*.33-z}}
function diamond(cx,cy,w,h,fill,stroke){ctx.beginPath();ctx.moveTo(cx,cy-h);ctx.lineTo(cx+w,cy);ctx.lineTo(cx,cy+h);ctx.lineTo(cx-w,cy);ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function drawFloor(){const tile=80,rangeX=Math.ceil(W/70)+4,rangeY=Math.ceil(H/40)+4,ix=Math.floor(player.x/tile),iy=Math.floor(player.y/tile);for(let gy=iy-rangeY;gy<=iy+rangeY;gy++)for(let gx=ix-rangeX;gx<=ix+rangeX;gx++){const wx=gx*tile,wy=gy*tile,p=project(wx,wy),alt=(gx+gy)&1;diamond(p.x,p.y,53,27,alt?'#292720':'#24221d','#3e382e');ctx.strokeStyle='#17130f';ctx.beginPath();ctx.moveTo(p.x-48,p.y+1);ctx.lineTo(p.x-8,p.y+20);ctx.lineTo(p.x+35,p.y-13);ctx.stroke()}}
function drawWall(r){const a=project(r.x,r.y),b=project(r.x+r.w,r.y),c=project(r.x+r.w,r.y+r.h),d=project(r.x,r.y+r.h),z=34;ctx.fillStyle='#17130f';ctx.beginPath();ctx.moveTo(a.x,a.y-z);ctx.lineTo(b.x,b.y-z);ctx.lineTo(c.x,c.y-z);ctx.lineTo(d.x,d.y-z);ctx.closePath();ctx.fill();ctx.strokeStyle='#82704f';ctx.stroke();ctx.fillStyle='#302c25';ctx.beginPath();ctx.moveTo(d.x,d.y-z);ctx.lineTo(c.x,c.y-z);ctx.lineTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.closePath();ctx.fill();ctx.fillStyle='#3d382f';ctx.beginPath();ctx.moveTo(b.x,b.y-z);ctx.lineTo(c.x,c.y-z);ctx.lineTo(c.x,c.y);ctx.lineTo(b.x,b.y);ctx.closePath();ctx.fill();ctx.strokeStyle='#17130f';for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(d.x+(c.x-d.x)*i/4,d.y-z+(c.y-d.y)*i/4);ctx.lineTo(d.x+(c.x-d.x)*i/4,d.y+(c.y-d.y)*i/4);ctx.stroke()}}
function ellipseShadow(sx,sy,rx,ry){ctx.fillStyle='#0009';ctx.beginPath();ctx.ellipse(sx+5,sy+9,rx,ry,0,0,Math.PI*2);ctx.fill()}
function healthBar(sx,sy,v,max,w=42){ctx.fillStyle='#160b08';ctx.fillRect(sx-w/2,sy,w,5);ctx.fillStyle='#b8392f';ctx.fillRect(sx-w/2,sy,w*Math.max(0,v/max),5);ctx.strokeStyle='#d1ad68';ctx.strokeRect(sx-w/2+.5,sy+.5,w-1,4)}
function drawGuardian(o,sx,sy,main){const bob=Math.sin(o.walk)*2,atk=o.attackT>0?1-o.attackT/.28:0;ellipseShadow(sx,sy,19,8);ctx.save();ctx.translate(sx,sy+bob);ctx.fillStyle='#172943';ctx.beginPath();ctx.moveTo(-12,-8);ctx.lineTo(-21,28);ctx.lineTo(14,25);ctx.lineTo(10,-7);ctx.fill();ctx.fillStyle='#9ea1a1';ctx.roundRect(-14,-18,28,31,7);ctx.fill();ctx.fillStyle='#5d6264';ctx.beginPath();ctx.arc(0,-27,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d2cfc4';ctx.beginPath();ctx.moveTo(-11,-30);ctx.lineTo(0,-43);ctx.lineTo(11,-30);ctx.closePath();ctx.fill();ctx.fillStyle='#762f20';ctx.beginPath();ctx.moveTo(0,-43);ctx.quadraticCurveTo(18,-48,20,-35);ctx.quadraticCurveTo(9,-40,1,-35);ctx.fill();ctx.fillStyle='#324f70';ctx.beginPath();ctx.ellipse(-18,-3,12,17,-.25,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#e1bb62';ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.translate(8,-5);ctx.rotate(-1.1+atk*2.1);ctx.strokeStyle='#e8e5da';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(35,-2);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle='#d2a94d';ctx.fillRect(-3,-5,8,10);ctx.restore();ctx.restore();healthBar(sx,sy-53,o.hp,o.maxHp,46)}
function drawRanger(o,sx,sy){const bob=Math.sin(o.walk)*2,atk=o.attackT>0?1-o.attackT/.22:0;ellipseShadow(sx,sy,17,7);ctx.save();ctx.translate(sx,sy+bob);ctx.fillStyle='#173d24';ctx.beginPath();ctx.moveTo(0,-38);ctx.lineTo(-19,27);ctx.lineTo(18,27);ctx.closePath();ctx.fill();ctx.fillStyle='#503522';ctx.fillRect(-10,-12,20,26);ctx.fillStyle='#122a1b';ctx.beginPath();ctx.arc(0,-25,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#caa87e';ctx.beginPath();ctx.arc(0,-23,7,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(10,-4);ctx.scale(1+atk*.16,1);ctx.strokeStyle='#d1aa59';ctx.lineWidth=4;ctx.beginPath();ctx.arc(8,0,21,-1.3,1.3);ctx.stroke();ctx.strokeStyle='#ede2b7';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(14,-20);ctx.lineTo(14,20);ctx.stroke();ctx.restore();ctx.restore();healthBar(sx,sy-51,o.hp,o.maxHp,40)}
function drawArcanist(o,sx,sy){const bob=Math.sin(o.walk)*2,cast=o.attackT>0?1:0;ellipseShadow(sx,sy,17,7);ctx.save();ctx.translate(sx,sy+bob);ctx.fillStyle='#1d3970';ctx.beginPath();ctx.moveTo(0,-38);ctx.lineTo(-20,28);ctx.lineTo(20,28);ctx.closePath();ctx.fill();ctx.fillStyle='#526da8';ctx.fillRect(-11,-13,22,28);ctx.fillStyle='#d6c6ad';ctx.beginPath();ctx.arc(0,-24,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#202641';ctx.beginPath();ctx.arc(0,-27,13,Math.PI,0);ctx.fill();ctx.strokeStyle='#799fff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(16,-15);ctx.lineTo(18,27);ctx.stroke();const g=ctx.createRadialGradient(16,-20,1,16,-20,16+cast*7);g.addColorStop(0,'#fff');g.addColorStop(.25,'#a7bdff');g.addColorStop(1,'#5e55ff00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(16,-20,16+cast*7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#794ca0';ctx.fillRect(-20,-8,10,15);ctx.restore();healthBar(sx,sy-51,o.hp,o.maxHp,40)}
function drawWarden(o,sx,sy){const bob=Math.sin(o.walk)*2,atk=o.attackT>0?1-o.attackT/.28:0;ellipseShadow(sx,sy,18,7);ctx.save();ctx.translate(sx,sy+bob);ctx.fillStyle='#e9e0c8';ctx.beginPath();ctx.moveTo(0,-37);ctx.lineTo(-19,28);ctx.lineTo(19,28);ctx.closePath();ctx.fill();ctx.fillStyle='#a58d55';ctx.fillRect(-11,-13,22,27);ctx.fillStyle='#e8ddbf';ctx.beginPath();ctx.arc(0,-26,11,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f1cf68';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,1,14,0,Math.PI*2);ctx.stroke();ctx.save();ctx.translate(9,-4);ctx.rotate(-.8+atk*1.8);ctx.strokeStyle='#c6a553';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(27,18);ctx.stroke();ctx.fillStyle='#e0c36f';ctx.fillRect(23,12,17,10);ctx.restore();ctx.restore();healthBar(sx,sy-51,o.hp,o.maxHp,40)}
function drawEnemy(e,sx,sy){const bob=Math.sin(e.walk)*1.8,atk=e.attackT>0?Math.sin((.26-e.attackT)/.26*Math.PI):0;ellipseShadow(sx,sy,e.r*1.05,7);ctx.save();ctx.translate(sx,sy+bob);if(e.flash)ctx.globalAlpha=.5;if(e.type==='skeleton'){ctx.strokeStyle='#ddd2b5';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,-16);ctx.lineTo(0,15);ctx.moveTo(-12,-2);ctx.lineTo(12,2);ctx.moveTo(0,14);ctx.lineTo(-9,29);ctx.moveTo(0,14);ctx.lineTo(10,29);ctx.stroke();ctx.fillStyle='#e3d6ba';ctx.beginPath();ctx.arc(0,-27,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1e0d0b';ctx.fillRect(-6,-30,4,4);ctx.fillRect(2,-30,4,4);ctx.fillStyle='#70452c';ctx.beginPath();ctx.ellipse(-15,-2,9,13,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(10,-5);ctx.rotate(-1+atk*1.7);ctx.strokeStyle='#b9b4aa';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(26,-8);ctx.stroke();ctx.restore()}else if(e.type==='goblin'){ctx.fillStyle='#536b39';ctx.beginPath();ctx.arc(0,-20,12,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-10,-25);ctx.lineTo(-22,-20);ctx.lineTo(-10,-14);ctx.fill();ctx.beginPath();ctx.moveTo(10,-25);ctx.lineTo(22,-20);ctx.lineTo(10,-14);ctx.fill();ctx.fillStyle='#5d3822';ctx.roundRect(-12,-8,24,26,6);ctx.fill();ctx.fillStyle='#ffbf3f';ctx.fillRect(-6,-23,4,3);ctx.fillRect(2,-23,4,3);ctx.save();ctx.rotate(atk*.55);ctx.strokeStyle='#c8beb2';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-12,-2);ctx.lineTo(-29,-16);ctx.moveTo(12,-2);ctx.lineTo(29,-16);ctx.stroke();ctx.restore()}else if(e.type==='ghoul'){ctx.fillStyle='#645448';ctx.beginPath();ctx.ellipse(0,0,19,26,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#826d59';ctx.beginPath();ctx.arc(0,-27,12,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#756252';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-12,-4);ctx.lineTo(-28,15+atk*10);ctx.moveTo(12,-4);ctx.lineTo(28,15-atk*10);ctx.stroke();ctx.fillStyle='#ef5b42';ctx.fillRect(-6,-30,4,4);ctx.fillRect(2,-30,4,4)}else{ctx.fillStyle='#3e2e29';ctx.beginPath();ctx.ellipse(0,2,30,32,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6d5749';ctx.beginPath();ctx.arc(0,-32,16,0,Math.PI*2);ctx.fill();ctx.fillStyle='#29231f';ctx.fillRect(-23,-8,46,17);ctx.fillStyle='#e94c3b';ctx.fillRect(-7,-36,5,4);ctx.fillRect(2,-36,5,4);ctx.save();ctx.translate(18,-4);ctx.rotate(-.8+atk*1.25);ctx.strokeStyle='#918981';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(33,-22);ctx.stroke();ctx.fillStyle='#59534c';ctx.fillRect(27,-30,22,14);ctx.restore()}ctx.restore();healthBar(sx,sy-e.r-42,e.hp,e.maxHp,e.r*2.1)}
function drawSpawner(s,sx,sy){const pulse=1+Math.sin(time*5)*.08;ellipseShadow(sx,sy,30,9);const g=ctx.createRadialGradient(sx,sy-22,2,sx,sy-22,52);g.addColorStop(0,'#fff');g.addColorStop(.2,'#d69cff');g.addColorStop(.55,'#7b31b0');g.addColorStop(1,'#24053200');ctx.fillStyle=g;ctx.beginPath();ctx.arc(sx,sy-22,52*pulse,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#cf83ff';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(sx,sy,30,13,time,0,Math.PI*2);ctx.stroke();healthBar(sx,sy-65,s.hp,150,54)}
function drawTorch(t){const p=project(t.x,t.y,18),f=Math.sin(time*12+t.x)*3,g=ctx.createRadialGradient(p.x,p.y,2,p.x,p.y,95+f);g.addColorStop(0,'#ffd77b88');g.addColorStop(1,'#ff7a0000');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,95,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffb33b';ctx.beginPath();ctx.moveTo(p.x,p.y-18-f);ctx.quadraticCurveTo(p.x-9,p.y,p.x,p.y+5);ctx.quadraticCurveTo(p.x+9,p.y,p.x,p.y-18-f);ctx.fill()}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#0b0907';ctx.fillRect(0,0,W,H);drawFloor();world.walls.forEach(drawWall);torches.forEach(drawTorch);const drawables=[];for(const s of spawners)if(s.hp>0)drawables.push({sort:s.x+s.y,fn:()=>{const p=project(s.x,s.y);drawSpawner(s,p.x,p.y)}});for(const p of pickups)drawables.push({sort:p.x+p.y,fn:()=>{const q=project(p.x,p.y,8);ellipseShadow(q.x,q.y,11,4);ctx.fillStyle='#a83227';ctx.beginPath();ctx.arc(q.x,q.y,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e3c071';ctx.fillRect(q.x-2,q.y-8,4,16)}});for(const e of enemies)drawables.push({sort:e.x+e.y,fn:()=>{const p=project(e.x,e.y);drawEnemy(e,p.x,p.y)}});for(const a of [...allies,player])drawables.push({sort:a.x+a.y,fn:()=>{const p=project(a.x,a.y);if(a.role==='Guardian')drawGuardian(a,p.x,p.y,a===player);else if(a.role==='Ranger')drawRanger(a,p.x,p.y);else if(a.role==='Arcanist')drawArcanist(a,p.x,p.y);else drawWarden(a,p.x,p.y)}});drawables.sort((a,b)=>a.sort-b.sort).forEach(d=>d.fn());for(const p of projectiles){const q=project(p.x,p.y,p.z),col=p.role==='Arcanist'?'#8faaff':'#e3d37f';ctx.fillStyle=col;ctx.shadowColor=col;ctx.shadowBlur=16;ctx.beginPath();ctx.arc(q.x,q.y,7,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}for(const s of slashes){const q=project(s.x,s.y,20),ang=Math.atan2(s.dy,s.dx);ctx.strokeStyle='#ffe1a0';ctx.lineWidth=11;ctx.shadowColor='#ff9e32';ctx.shadowBlur=18;ctx.beginPath();ctx.arc(q.x,q.y,58,ang-.9,ang+.9);ctx.stroke();ctx.shadowBlur=0}for(const p of particles){const q=project(p.x,p.y,p.z);ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(q.x,q.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;const vg=ctx.createRadialGradient(W/2,H/2,Math.min(W,H)*.2,W/2,H/2,Math.max(W,H)*.7);vg.addColorStop(.5,'#0000');vg.addColorStop(1,'#000b');ctx.fillStyle=vg;ctx.fillRect(0,0,W,H);if(gameOver){ctx.fillStyle='#090604df';ctx.fillRect(0,0,W,H);ctx.fillStyle='#ead4a0';ctx.textAlign='center';ctx.font='bold 42px Georgia';ctx.fillText('YOU HAVE FALLEN',W/2,H/2);ctx.font='18px Georgia';ctx.fillText('Refresh to begin another run',W/2,H/2+36);ctx.textAlign='left'}}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
