'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),soundGate=document.getElementById('soundGate');
let W=innerWidth,H=innerHeight,last=performance.now(),time=0,score=0,over=false,audio=null;
const keys=new Set(),joy={on:false,id:null,bx:110,by:0,dx:0,dy:0},atk={on:false,id:null};
const world={w:1500,h:950};
const hero={x:330,y:330,hp:100,max:100,s:210,dx:1,dy:0,walk:0,attack:0,role:'Guardian'};
const allies=[mk(280,390,'Ranger',195),mk(245,300,'Arcanist',175),mk(335,420,'Warden',180)];
const enemies=[],shots=[],fx=[],portals=[{x:1120,y:260,hp:160,t:0},{x:1200,y:700,hp:160,t:0}];
function mk(x,y,role,s){return{x,y,hp:70,max:70,s,dx:1,dy:0,walk:Math.random()*6,attack:0,role}}
function resize(){W=innerWidth;H=innerHeight;canvas.width=W;canvas.height=H;canvas.style.width=W+'px';canvas.style.height=H+'px';joy.by=H-92}
addEventListener('resize',resize);resize();
function unlock(){try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();tone(520,.04,.05,'sine');soundGate.textContent='Sound on';setTimeout(()=>soundGate.classList.add('hidden'),350)}catch(e){soundGate.textContent='Sound unavailable'}}
soundGate.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();unlock()});
function tone(f,d=.08,v=.05,type='triangle'){if(!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function sfx(k){if(k==='swing'){tone(180,.09,.06,'sawtooth');setTimeout(()=>tone(110,.05,.025,'square'),35)}else if(k==='hit'){tone(72,.07,.09,'square')}else if(k==='magic'){tone(560,.12,.045,'sine');setTimeout(()=>tone(840,.1,.03,'sine'),40)}else if(k==='arrow'){tone(380,.06,.03,'triangle')}}
canvas.addEventListener('pointerdown',e=>{unlock();canvas.setPointerCapture(e.pointerId);if(e.clientX<W*.5&&!joy.on){joy.on=true;joy.id=e.pointerId;joy.bx=e.clientX;joy.by=e.clientY}else if(!atk.on){atk.on=true;atk.id=e.pointerId;swing(hero)}});
canvas.addEventListener('pointermove',e=>{if(e.pointerId!==joy.id)return;let dx=e.clientX-joy.bx,dy=e.clientY-joy.by,m=Math.hypot(dx,dy),l=48;if(m>l){dx*=l/m;dy*=l/m}joy.dx=dx/l;joy.dy=dy/l});
function release(e){if(e.pointerId===joy.id){joy.on=false;joy.id=null;joy.dx=joy.dy=0}if(e.pointerId===atk.id){atk.on=false;atk.id=null}}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.code==='Space')swing(hero)});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function nearest(a,list){let b=null,d=1e12;for(const q of list){let n=(q.x-a.x)**2+(q.y-a.y)**2;if(n<d){d=n;b=q}}return b}
function burst(x,y,c,n=8){for(let i=0;i<n;i++){let a=Math.random()*7,v=35+Math.random()*100;fx.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.3,max:.3,c,r:2+Math.random()*3})}}
function swing(a){if(a.attack>0||over)return;a.attack=.28;sfx('swing');for(const e of enemies){let dx=e.x-a.x,dy=e.y-a.y,d=Math.hypot(dx,dy)||1;if(d<105&&(dx*a.dx+dy*a.dy)/d>.05){e.hp-=38;e.flash=.12;burst(e.x,e.y,'#c33',10);sfx('hit')}}}
function shoot(a,e){let dx=e.x-a.x,dy=e.y-a.y,m=Math.hypot(dx,dy)||1;shots.push({x:a.x,y:a.y,vx:dx/m*390,vy:dy/m*390,life:1.6,role:a.role});a.attack=.22;sfx(a.role==='Arcanist'?'magic':'arrow')}
function spawn(p){let r=Math.random(),type=r<.48?'skeleton':r<.72?'goblin':r<.9?'ghoul':'brute',st={skeleton:[46,92],goblin:[34,128],ghoul:[62,102],brute:[130,62]}[type];enemies.push({x:p.x+(Math.random()-.5)*70,y:p.y+(Math.random()-.5)*70,hp:st[0],max:st[0],s:st[1],type,dx:-1,dy:0,walk:Math.random()*6,attack:0,flash:0})}
function update(dt){time+=dt;if(over)return;hero.attack=Math.max(0,hero.attack-dt);let mx=(keys.has('d')?1:0)-(keys.has('a')?1:0)+joy.dx,my=(keys.has('s')?1:0)-(keys.has('w')?1:0)+joy.dy,m=Math.hypot(mx,my);if(m>1){mx/=m;my/=m}if(m>.05){hero.dx=mx;hero.dy=my;hero.x+=mx*hero.s*dt;hero.y+=my*hero.s*dt;hero.walk+=dt*10}hero.x=Math.max(80,Math.min(world.w-80,hero.x));hero.y=Math.max(80,Math.min(world.h-80,hero.y));if(atk.on&&hero.attack<=0)swing(hero);
for(const a of allies){a.attack=Math.max(0,a.attack-dt);let e=nearest(a,enemies),dx=hero.x-a.x,dy=hero.y-a.y,d=Math.hypot(dx,dy)||1;if(e&&Math.hypot(e.x-a.x,e.y-a.y)<260){let ex=e.x-a.x,ey=e.y-a.y,em=Math.hypot(ex,ey)||1;a.dx=ex/em;a.dy=ey/em;if(a.attack<=0){if(a.role==='Warden'){e.hp-=24;e.flash=.1;a.attack=.65;sfx('hit')}else shoot(a,e)}}else if(d>72){a.x+=dx/d*a.s*dt;a.y+=dy/d*a.s*dt;a.walk+=dt*9}}
for(const p of portals){if(p.hp<=0)continue;p.t-=dt;if(p.t<=0){spawn(p);p.t=1.2+Math.random()*.8}}
for(const e of enemies){e.attack=Math.max(0,e.attack-dt);e.flash=Math.max(0,e.flash-dt);let a=nearest(e,[hero,...allies]),dx=a.x-e.x,dy=a.y-e.y,d=Math.hypot(dx,dy)||1;e.dx=dx/d;e.dy=dy/d;e.x+=e.dx*e.s*dt;e.y+=e.dy*e.s*dt;e.walk+=dt*8;if(d<42&&e.attack<=0){a.hp-=e.type==='brute'?16:8;e.attack=.7;burst(a.x,a.y,'#922',7);sfx('hit');if(a===hero&&a.hp<=0)over=true}}
for(const q of shots){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;for(const e of enemies)if(e.hp>0&&Math.hypot(e.x-q.x,e.y-q.y)<28){e.hp-=q.role==='Arcanist'?26:18;e.flash=.1;q.life=0;burst(e.x,e.y,q.role==='Arcanist'?'#7af':'#dbb86b',8);sfx('hit');break}}
for(const e of enemies)if(e.hp<=0&&!e.dead){e.dead=true;score+=e.type==='brute'?80:25;burst(e.x,e.y,'#641818',14)}
enemies.splice(0,enemies.length,...enemies.filter(e=>e.hp>0));shots.splice(0,shots.length,...shots.filter(q=>q.life>0));for(const q of fx){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;q.vx*=.94;q.vy*=.94}fx.splice(0,fx.length,...fx.filter(q=>q.life>0))}
function iso(wx,wy,cx,cy){return{x:W*.5+(wx-cx)*.72-(wy-cy)*.72,y:H*.52+(wx-cx)*.34+(wy-cy)*.34}}
function diamond(px,py,w,h,fill,stroke){ctx.fillStyle=fill;ctx.beginPath();ctx.moveTo(px,py-h);ctx.lineTo(px+w,py);ctx.lineTo(px,py+h);ctx.lineTo(px-w,py);ctx.closePath();ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function drawFloor(cx,cy){for(let gy=-7;gy<8;gy++)for(let gx=-10;gx<11;gx++){let wx=cx+gx*64,wy=cy+gy*64,p=iso(wx,wy,cx,cy),odd=(gx+gy)&1;diamond(p.x,p.y,47,22,odd?'#28241f':'#211e1a','#41382d');if((gx*7+gy*11)%9===0){ctx.strokeStyle='#5a4735';ctx.beginPath();ctx.moveTo(p.x-12,p.y-2);ctx.lineTo(p.x+4,p.y+5);ctx.lineTo(p.x+14,p.y-3);ctx.stroke()}}}
function wallBlock(wx,wy,cx,cy,len=3){for(let i=0;i<len;i++){let p=iso(wx+i*64,wy,cx,cy);diamond(p.x,p.y-22,47,22,'#494238','#6f5a3b');ctx.fillStyle='#211c18';ctx.beginPath();ctx.moveTo(p.x-47,p.y-22);ctx.lineTo(p.x,p.y);ctx.lineTo(p.x,p.y+30);ctx.lineTo(p.x-47,p.y+8);ctx.fill();ctx.fillStyle='#332d26';ctx.beginPath();ctx.moveTo(p.x+47,p.y-22);ctx.lineTo(p.x,p.y);ctx.lineTo(p.x,p.y+30);ctx.lineTo(p.x+47,p.y+8);ctx.fill()}}
function actor(o,cx,cy,isHero=false){let p=iso(o.x,o.y,cx,cy),bob=Math.sin(o.walk)*2,attack=o.attack>0?Math.sin((.28-o.attack)/.28*Math.PI):0,sc=o.type==='brute'?1.35:1;ctx.save();ctx.translate(p.x,p.y);ctx.scale(sc,sc);ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,13,18,7,0,0,7);ctx.fill();if(o.flash)ctx.globalAlpha=.45;
if(isHero){ctx.fillStyle='#173a67';ctx.beginPath();ctx.moveTo(-13,-7+bob);ctx.lineTo(-20,23);ctx.lineTo(15,18);ctx.lineTo(12,-6+bob);ctx.fill();ctx.fillStyle='#9ca2a5';ctx.fillRect(-12,-12+bob,24,25);ctx.fillStyle='#d2d4d0';ctx.beginPath();ctx.arc(0,-18+bob,11,0,7);ctx.fill();ctx.fillStyle='#8d1f18';ctx.beginPath();ctx.moveTo(0,-30+bob);ctx.quadraticCurveTo(16,-36+bob,18,-23+bob);ctx.lineTo(2,-20+bob);ctx.fill();ctx.fillStyle='#3d5874';ctx.beginPath();ctx.ellipse(-17,1+bob,10,14,-.25,0,7);ctx.fill();ctx.strokeStyle='#d7b45d';ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.translate(11,0+bob);ctx.rotate(-.7+attack*1.7);ctx.strokeStyle='#f1ead7';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(30,-13);ctx.stroke();ctx.strokeStyle='#d5ad52';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-3,-2);ctx.lineTo(6,5);ctx.stroke();ctx.restore()}
else if(o.role==='Ranger'){ctx.fillStyle='#183f27';ctx.beginPath();ctx.moveTo(0,-27+bob);ctx.lineTo(-18,22);ctx.lineTo(18,22);ctx.fill();ctx.fillStyle='#bb946b';ctx.beginPath();ctx.arc(0,-14+bob,7,0,7);ctx.fill();ctx.strokeStyle='#d0a755';ctx.lineWidth=3;ctx.beginPath();ctx.arc(15,0,18,-1.3,1.3);ctx.stroke();ctx.strokeStyle='#eee1b8';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(18,-17);ctx.lineTo(18,17);ctx.stroke()}
else if(o.role==='Arcanist'){ctx.fillStyle='#233f7f';ctx.beginPath();ctx.moveTo(0,-28+bob);ctx.lineTo(-18,22);ctx.lineTo(18,22);ctx.fill();ctx.fillStyle='#d6c3aa';ctx.beginPath();ctx.arc(0,-15+bob,7,0,7);ctx.fill();ctx.strokeStyle='#7fb0ff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(15,-12);ctx.lineTo(17,22);ctx.stroke();ctx.fillStyle='#b8d2ff';ctx.beginPath();ctx.arc(15,-15,6+Math.sin(time*8)*2,0,7);ctx.fill()}
else if(o.role==='Warden'){ctx.fillStyle='#eee2c9';ctx.beginPath();ctx.moveTo(0,-25+bob);ctx.lineTo(-18,22);ctx.lineTo(18,22);ctx.fill();ctx.fillStyle='#b49449';ctx.fillRect(-10,-7,20,20);ctx.strokeStyle='#e8c765';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(12,-2);ctx.lineTo(27,18);ctx.stroke();ctx.fillStyle='#d9c475';ctx.fillRect(22,12,13,8)}
else if(o.type==='skeleton'){ctx.strokeStyle='#ddd2b8';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(0,13);ctx.moveTo(-12,-2);ctx.lineTo(12,4);ctx.moveTo(0,13);ctx.lineTo(-9,26);ctx.moveTo(0,13);ctx.lineTo(9,26);ctx.stroke();ctx.fillStyle='#e3d7bd';ctx.beginPath();ctx.arc(0,-18,9,0,7);ctx.fill();ctx.fillStyle='#24120e';ctx.fillRect(-5,-20,3,3);ctx.fillRect(2,-20,3,3);ctx.strokeStyle='#aaa59a';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(11,1);ctx.lineTo(23,-17);ctx.stroke();ctx.fillStyle='#68432e';ctx.beginPath();ctx.ellipse(-14,2,8,11,0,0,7);ctx.fill()}
else if(o.type==='goblin'){ctx.fillStyle='#536b36';ctx.beginPath();ctx.arc(0,-12,10,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-8,-15);ctx.lineTo(-18,-11);ctx.lineTo(-8,-6);ctx.fill();ctx.beginPath();ctx.moveTo(8,-15);ctx.lineTo(18,-11);ctx.lineTo(8,-6);ctx.fill();ctx.fillStyle='#5b3520';ctx.fillRect(-10,-2,20,21);ctx.strokeStyle='#d2cbc0';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-11,3);ctx.lineTo(-22,-8);ctx.moveTo(11,3);ctx.lineTo(22,-8);ctx.stroke()}
else{ctx.fillStyle=o.type==='brute'?'#49332a':'#6c5849';ctx.beginPath();ctx.ellipse(0,1,o.type==='brute'?25:17,o.type==='brute'?27:20,0,0,7);ctx.fill();ctx.fillStyle='#806755';ctx.beginPath();ctx.arc(0,o.type==='brute'?-22:-16,o.type==='brute'?13:10,0,7);ctx.fill();ctx.fillStyle='#e94d3d';ctx.fillRect(-6,o.type==='brute'?-24:-18,4,3);ctx.fillRect(2,o.type==='brute'?-24:-18,4,3);ctx.strokeStyle='#93877d';ctx.lineWidth=o.type==='brute'?7:4;ctx.beginPath();ctx.moveTo(15,0);ctx.lineTo(o.type==='brute'?35:25,-20);ctx.stroke()}ctx.restore();barAt(p.x,p.y-45,o.hp,o.max,isHero?'#c0392b':'#9d2b25')}
function barAt(x,y,v,max,c){ctx.fillStyle='#160b08';ctx.fillRect(x-22,y,44,5);ctx.fillStyle=c;ctx.fillRect(x-22,y,44*Math.max(0,v/max),5);ctx.strokeStyle='#b49355';ctx.strokeRect(x-22,y,44,5)}
function portal(p,cx,cy){let q=iso(p.x,p.y,cx,cy),g=ctx.createRadialGradient(q.x,q.y,2,q.x,q.y,60);g.addColorStop(0,'#f5b5ff');g.addColorStop(.3,'#8d36bd');g.addColorStop(1,'#2b0b3800');ctx.fillStyle=g;ctx.beginPath();ctx.arc(q.x,q.y,60,0,7);ctx.fill();ctx.strokeStyle='#cf7eff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(q.x,q.y,30,time,time+5);ctx.stroke();barAt(q.x,q.y-48,p.hp,160,'#9c4db5')}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#080706';ctx.fillRect(0,0,W,H);let cx=hero.x,cy=hero.y;drawFloor(cx,cy);wallBlock(cx-420,cy-260,cx,cy,5);wallBlock(cx+160,cy-320,cx,cy,4);wallBlock(cx-520,cy+260,cx,cy,4);portals.filter(p=>p.hp>0).forEach(p=>portal(p,cx,cy));let list=[...enemies,...allies,hero].sort((a,b)=>(a.x+a.y)-(b.x+b.y));for(const o of list)actor(o,cx,cy,o===hero);for(const q of shots){let p=iso(q.x,q.y,cx,cy),c=q.role==='Arcanist'?'#81aaff':'#f0d07b';ctx.fillStyle=c;ctx.shadowColor=c;ctx.shadowBlur=14;ctx.beginPath();ctx.arc(p.x,p.y,7,0,7);ctx.fill();ctx.shadowBlur=0}for(const q of fx){let p=iso(q.x,q.y,cx,cy);ctx.globalAlpha=q.life/q.max;ctx.fillStyle=q.c;ctx.beginPath();ctx.arc(p.x,p.y,q.r,0,7);ctx.fill()}ctx.globalAlpha=1;let v=ctx.createRadialGradient(W/2,H/2,120,W/2,H/2,Math.max(W,H)*.7);v.addColorStop(.45,'#0000');v.addColorStop(1,'#000c');ctx.fillStyle=v;ctx.fillRect(0,0,W,H);if(over){ctx.fillStyle='#080604df';ctx.fillRect(0,0,W,H);ctx.fillStyle='#ead4a0';ctx.textAlign='center';ctx.font='bold 42px Georgia';ctx.fillText('YOU HAVE FALLEN',W/2,H/2)}}
function loop(n){let dt=Math.min(.033,(n-last)/1000);last=n;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);