(()=>{
'use strict';
const API='https://api.inaturalist.org/v1/observations';
const POS='ctd_last_pos_v1';
const CACHE='ctd_public_bear_obs_v1';
const BROWN=41641,BLACK=41638;
const RADIUS_MI=50,RADIUS_KM=Math.round(RADIUS_MI*1.60934),DAYS=30;
let here=null,data=null;
const $=id=>document.getElementById(id);
function hav(a,b,c,d){const R=3958.8,q=x=>x*Math.PI/180,da=q(c-a),db=q(d-b),s=Math.sin(da/2)**2+Math.cos(q(a))*Math.cos(q(c))*Math.sin(db/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
function cachedPos(){try{let p=JSON.parse(localStorage.getItem(POS)||'null');if(Number.isFinite(+p?.lat)&&Number.isFinite(+p?.lon))return{lat:+p.lat,lon:+p.lon,saved:+p.saved||0}}catch{}return null}
async function getPos(){let p=cachedPos();if(p&&Date.now()-p.saved<10*60*1000)return p;if(!navigator.geolocation)return p;try{let g=await new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(ok,no,{enableHighAccuracy:true,timeout:12000,maximumAge:300000}));return{lat:g.coords.latitude,lon:g.coords.longitude,saved:Date.now()}}catch{return p}}
function cutoff(){let d=new Date(Date.now()-DAYS*864e5);return d.toISOString().slice(0,10)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function obsTime(o){let s=o?.time_observed_at||o?.observed_on;let t=Date.parse(s||'');return Number.isFinite(t)?t:0}
function age(t){if(!t)return'unknown date';let m=Math.max(0,Math.floor((Date.now()-t)/60000));if(m<60)return`${Math.max(1,m)} min ago`;let h=Math.floor(m/60);if(h<24)return`${h} hr${h===1?'':'s'} ago`;let d=Math.floor(h/24);return`${d} day${d===1?'':'s'} ago`}
function coords(o){let c=o?.geojson?.coordinates;if(Array.isArray(c)&&c.length>=2&&Number.isFinite(+c[0])&&Number.isFinite(+c[1]))return{lat:+c[1],lon:+c[0]};if(typeof o?.location==='string'){let a=o.location.split(',').map(Number);if(a.length===2&&a.every(Number.isFinite))return{lat:a[0],lon:a[1]}}return null}
function species(o){let n=(o?.taxon?.name||'').toLowerCase(),common=o?.taxon?.preferred_common_name||o?.species_guess||'';if(n.includes('americanus')||String(common).toLowerCase().includes('black bear'))return{icon:'⚫',name:'Black bear'};if(n.includes('arctos')||String(common).toLowerCase().includes('brown')||String(common).toLowerCase().includes('grizzly'))return{icon:'🟤',name:'Brown / grizzly'};return{icon:'🐻',name:common||'Bear'}}
function normalize(raw){let a=Array.isArray(raw?.results)?raw.results:[];return a.map(o=>{let c=coords(o),t=obsTime(o),s=species(o),m=c&&here?hav(here.lat,here.lon,c.lat,c.lon):null;return{id:o.id,uri:o.uri||`https://www.inaturalist.org/observations/${o.id}`,observed:t,observed_text:o.observed_on||'',created:Date.parse(o.created_at||'')||0,place:o.place_guess||'',accuracy:+o.positional_accuracy||+o.public_positional_accuracy||null,geoprivacy:o.geoprivacy||null,lat:c?.lat,lon:c?.lon,miles:m,icon:s.icon,species:s.name,quality:o.quality_grade||''}}).filter(x=>x.observed&&Date.now()-x.observed<=DAYS*864e5+864e5).sort((a,b)=>b.observed-a.observed)}
function injectStyles(){let s=document.createElement('style');s.textContent=`.bearPanel{margin:12px 0 0;padding:13px 14px;border:1px solid #323740;border-left:5px solid #c8a45a;border-radius:17px;background:linear-gradient(105deg,#c8a45a12,#ffffff04);box-shadow:0 12px 28px #0003}.bearTop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.bearKicker{color:#c8a45a;font-size:9px;font-weight:900;letter-spacing:.14em;text-transform:uppercase}.bearHeadline{margin-top:4px;color:#f5f3ef;font-size:17px;font-weight:850;line-height:1.2}.bearBadge{flex:none;border:1px solid #c8a45a66;border-radius:999px;padding:5px 7px;color:#e4c77f;font-size:8px;font-weight:900;letter-spacing:.08em}.bearBadge.hot{border-color:#c96b62;color:#e7a099}.bearBadge.clear{border-color:#68717d;color:#afb5bd}.bearPublic{margin-top:9px;padding:9px 10px;border:1px solid #323740;border-radius:13px;background:#0f111566}.bearPublicLabel{color:#9299a3;font-size:8px;font-weight:900;letter-spacing:.09em;text-transform:uppercase}.bearLatest{margin-top:4px;color:#d9dde2;font-size:11px;line-height:1.45}.bearStats{margin-top:4px;color:#9299a3;font-size:9px}.bearActions{display:flex;gap:7px;margin-top:10px}.bearActions button,.bearActions a{display:inline-flex;align-items:center;justify-content:center;flex:1;border-radius:999px;padding:10px 11px;font-weight:900;font-size:9px;letter-spacing:.03em;text-decoration:none}.bearView{border:1px solid #323740;background:#ffffff08;color:#d9dde2}.bearSource{border:1px solid #c8a45a66;background:#c8a45a12;color:#e4c77f}.bearFine{margin-top:8px;color:#757d87;font-size:8px;line-height:1.45}.bearModal{position:fixed;inset:0;z-index:45;display:grid;place-items:end center;padding:16px;background:#000b;backdrop-filter:blur(7px)}.bearModal[hidden]{display:none}.bearSheet{width:min(100%,620px);max-height:82vh;overflow:auto;border:1px solid #323740;border-radius:24px 24px 18px 18px;background:#171a1f;padding:18px;box-shadow:0 25px 70px #000a}.bearSheet h2{margin:0;color:#f5f3ef;font-size:22px}.bearSub{margin-top:5px;color:#9299a3;font-size:10px;line-height:1.4}.bearList{display:grid;gap:8px;margin-top:12px}.bearItem{border:1px solid #323740;border-radius:15px;background:#ffffff06;padding:11px}.bearItemTop{display:flex;justify-content:space-between;gap:8px}.bearSpecies{font-weight:850;font-size:14px}.bearDist{color:#e4c77f;font-size:9px;font-weight:850}.bearMeta{margin-top:4px;color:#9299a3;font-size:9px}.bearPlace{margin-top:6px;color:#d9dde2;font-size:10px;line-height:1.35}.bearLink{display:inline-block;margin-top:7px;color:#d9dde2;font-size:9px;text-decoration:none;border-bottom:1px solid #ffffff33}.bearClose{width:100%;margin-top:12px;border:1px solid #323740;border-radius:999px;padding:11px;background:#ffffff08;color:#d9dde2;font-weight:900;font-size:10px}@media(max-width:390px){.bearActions{display:grid;grid-template-columns:1fr}}`;document.head.appendChild(s)}
function searchUrl(){if(!here)return'https://www.inaturalist.org/observations?taxon_ids=41641,41638';return`https://www.inaturalist.org/observations?taxon_ids=${BROWN},${BLACK}&lat=${here.lat}&lng=${here.lon}&radius=${RADIUS_KM}&d1=${cutoff()}&order_by=observed_on&order=desc`}
function injectUI(){const host=$('eventBanner')||document.querySelector('header .thought')||document.querySelector('header');if(!host||$('bearPanel'))return;let p=document.createElement('section');p.id='bearPanel';p.className='bearPanel';p.innerHTML=`<div class="bearTop"><div><div class="bearKicker">BEAR ACTIVITY</div><div class="bearHeadline" id="bearHeadline">Checking active bear signals…</div></div><span class="bearBadge clear" id="bearBadge">PUBLIC</span></div><div class="bearPublic"><div class="bearPublicLabel">RECENT PUBLIC OBSERVATIONS</div><div class="bearLatest" id="bearLatest">Looking for recent brown/grizzly and black bear observations near your GPS.</div><div class="bearStats" id="bearStats"></div></div><div class="bearActions"><button class="bearView" id="bearView" type="button">VIEW RECENT</button><a class="bearSource" id="bearSource" target="_blank" rel="noopener">OPEN iNATURALIST ↗</a></div><div class="bearFine">Public iNaturalist observations, not an emergency dispatch feed. Observation gaps do not mean bears are absent.</div>`;host.insertAdjacentElement('afterend',p);document.body.insertAdjacentHTML('beforeend',`<div class="bearModal" id="bearModal" hidden><div class="bearSheet"><div class="bearKicker">RECENT PUBLIC OBSERVATIONS</div><h2>Bears near this GPS</h2><div class="bearSub">Brown/grizzly and black bear observations from the last ${DAYS} days within about ${RADIUS_MI} miles. Times below are observation times, not upload times.</div><div class="bearList" id="bearList"></div><button class="bearClose" id="bearClose" type="button">CLOSE</button></div></div>`);$('bearView').onclick=()=>{renderList();$('bearModal').hidden=false};$('bearClose').onclick=()=>{$('bearModal').hidden=true};$('bearModal').onclick=e=>{if(e.target===$('bearModal'))$('bearModal').hidden=true}}
function render(){if(!$('bearHeadline'))return;$('bearSource').href=searchUrl();if(!here){$('bearHeadline').textContent='Location needed for nearby bear activity';$('bearLatest').textContent='Allow location so recent public bear observations can be filtered around you.';$('bearStats').textContent='';return}let a=normalize(data||{}),w7=a.filter(x=>Date.now()-x.observed<=7*864e5),w3=a.filter(x=>Date.now()-x.observed<=3*864e5),near3=w3.filter(x=>x.miles!=null&&x.miles<=15),near7=w7.filter(x=>x.miles!=null&&x.miles<=25),badge=$('bearBadge');if(!a.length){$('bearHeadline').textContent=`No public bear observations within ${RADIUS_MI} mi in ${DAYS} days`;$('bearLatest').textContent='No recent iNaturalist bear observation was returned for this area.';$('bearStats').textContent='This does not mean there are no bears.';badge.textContent='NO RECENT OBS';badge.className='bearBadge clear';return}let focus=(near3.sort((x,y)=>(x.miles-y.miles)||y.observed-x.observed)[0])||(near7.sort((x,y)=>y.observed-x.observed)[0])||a[0],dist=focus.miles==null?'distance unavailable':`${focus.miles.toFixed(1)} mi`,privacy=focus.geoprivacy?' · location may be obscured':'';$('bearHeadline').textContent=near3.length?`${near3.length} very recent bear observation${near3.length===1?'':'s'} nearby`:w7.length?`${w7.length} bear observation${w7.length===1?'':'s'} in the last 7 days`:`${a.length} bear observation${a.length===1?'':'s'} in the last ${DAYS} days`;$('bearLatest').textContent=`${focus.icon} ${focus.species} · ${dist} · observed ${age(focus.observed)}${focus.place?` · ${focus.place}`:''}${privacy}`;$('bearStats').textContent=`Last 3 days: ${w3.length} · Last 7 days: ${w7.length} · Last ${DAYS} days: ${a.length}`;if(near3.length){badge.textContent='VERY RECENT';badge.className='bearBadge hot'}else if(near7.length){badge.textContent='RECENT';badge.className='bearBadge'}else{badge.textContent='LAST 30 DAYS';badge.className='bearBadge clear'}}
function renderList(){let box=$('bearList'),a=normalize(data||{}).slice(0,30);if(!a.length){box.innerHTML='<div class="bearItem"><div class="bearPlace">No public bear observations were returned in the current search window.</div></div>';return}box.innerHTML='';for(let r of a){let d=document.createElement('div');d.className='bearItem';d.innerHTML=`<div class="bearItemTop"><div class="bearSpecies">${r.icon} ${esc(r.species)}</div><div class="bearDist">${r.miles==null?'—':r.miles.toFixed(1)+' mi'}</div></div><div class="bearMeta">Observed ${esc(age(r.observed))}${r.quality?` · ${esc(r.quality)}`:''}${r.geoprivacy?' · obscured location':''}</div>${r.place?`<div class="bearPlace">${esc(r.place)}</div>`:''}<a class="bearLink" href="${esc(r.uri)}" target="_blank" rel="noopener">OPEN OBSERVATION ↗</a>`;box.appendChild(d)}}
function cached(){try{return JSON.parse(localStorage.getItem(CACHE)||'null')}catch{return null}}
async function refresh(){here=await getPos();render();if(!here)return;let c=cached();if(!navigator.onLine){if(c?.raw)data=c.raw;render();return}let q=new URLSearchParams({lat:String(here.lat),lng:String(here.lon),radius:String(RADIUS_KM),taxon_id:`${BROWN},${BLACK}`,d1:cutoff(),order:'desc',order_by:'observed_on',per_page:'100',geo:'true',verifiable:'true'});try{let r=await fetch(`${API}?${q}`,{cache:'no-store'});if(!r.ok)throw Error(`iNaturalist ${r.status}`);let raw=await r.json();data=raw;localStorage.setItem(CACHE,JSON.stringify({saved:Date.now(),lat:here.lat,lon:here.lon,raw}));render()}catch{if(c?.raw){data=c.raw;render()}else{$('bearLatest').textContent='Recent public bear observations are temporarily unavailable.';$('bearStats').textContent='Official alert and known-area information remain available.'}}}
async function init(){try{localStorage.removeItem('ctd_bear_reports_v1')}catch{}injectStyles();injectUI();await refresh()}
window.addEventListener('online',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});setInterval(refresh,15*60*1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
