(()=>{
'use strict';
const ALERT_URL='https://raw.githubusercontent.com/Alterx3509/cryptbound/main/cross-the-divide/bear-alerts.json';
const ALERTS_PAGE='https://www.fs.usda.gov/r10/chugach/alerts';
const ADFG_RUSSIAN='https://www.adfg.alaska.gov/index.cfm?adfg=livingwithbears.russianriver';
const CACHE='ctd_official_bear_alerts_v1';
const POS='ctd_last_pos_v1';
const RUSSIAN={name:'Russian River / Kenai confluence',lat:60.4154,lon:-149.9947,radius:18};
let lastData=null;
const $=id=>document.getElementById(id);
function hav(a,b,c,d){const R=3958.8,q=x=>x*Math.PI/180,da=q(c-a),db=q(d-b),s=Math.sin(da/2)**2+Math.cos(q(a))*Math.cos(q(c))*Math.sin(db/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
function cachedPos(){try{let p=JSON.parse(localStorage.getItem(POS)||'null');if(Number.isFinite(+p?.lat)&&Number.isFinite(+p?.lon))return{lat:+p.lat,lon:+p.lon}}catch{}return null}
function cachedAlerts(){try{return JSON.parse(localStorage.getItem(CACHE)||'null')}catch{return null}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function inject(){let panel=$('bearPanel');if(!panel||$('bearOfficial'))return false;let style=document.createElement('style');style.textContent=`.bearIntel{display:grid;gap:7px;margin-top:10px}.bearIntelRow{border:1px solid #323740;border-radius:13px;background:#0f111566;padding:9px 10px}.bearIntelRow.alert{border-color:#c96b6288;background:#c96b6212}.bearIntelRow.known{border-color:#c8a45a66;background:#c8a45a0d}.bearIntelLabel{color:#9299a3;font-size:8px;font-weight:900;letter-spacing:.09em;text-transform:uppercase}.bearIntelText{margin-top:3px;color:#d9dde2;font-size:10px;line-height:1.35}.bearIntelText strong{color:#f5f3ef}.bearIntelLink{display:inline-block;margin-top:5px;color:#bfc5cc;font-size:8px;text-decoration:none;border-bottom:1px solid #ffffff2b}`;document.head.appendChild(style);let wrap=document.createElement('div');wrap.id='bearOfficial';wrap.className='bearIntel';wrap.innerHTML=`<div class="bearIntelRow" id="bearOfficialRow"><div class="bearIntelLabel">OFFICIAL STATUS</div><div class="bearIntelText" id="bearOfficialText">Checking Chugach National Forest alerts…</div><a class="bearIntelLink" href="${ALERTS_PAGE}" target="_blank" rel="noopener">VIEW OFFICIAL ALERTS ↗</a></div><div class="bearIntelRow" id="bearKnownRow"><div class="bearIntelLabel">KNOWN BEAR AREA</div><div class="bearIntelText" id="bearKnownText">Checking location against ADF&amp;G bear-awareness areas…</div><a class="bearIntelLink" id="bearKnownLink" href="${ADFG_RUSSIAN}" target="_blank" rel="noopener">ADF&amp;G GUIDANCE ↗</a></div>`;let top=panel.querySelector('.bearTop');top.insertAdjacentElement('afterend',wrap);return true}
function fmtChecked(ts){let d=new Date(ts);if(isNaN(d))return'';return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(d)}
function renderOfficial(data){if(!inject())return;lastData=data||lastData;let row=$('bearOfficialRow'),box=$('bearOfficialText'),alerts=Array.isArray(data?.alerts)?data.alerts:[];row.className='bearIntelRow'+(alerts.length?' alert':'');if(alerts.length){let a=alerts[0];box.innerHTML=`<strong>${esc(a.title||'Bear-related official alert')}</strong>${a.summary?` · ${esc(a.summary)}`:''}${data?.checked_at?`<br>Checked ${esc(fmtChecked(data.checked_at))}`:''}`;let link=row.querySelector('a');link.href=a.url||ALERTS_PAGE;link.textContent='OPEN OFFICIAL NOTICE ↗'}else if(data){box.innerHTML=`No bear-specific Chugach Forest alert found in the current alert list.${data.checked_at?` <span style="color:#9299a3">Checked ${esc(fmtChecked(data.checked_at))}.</span>`:''}`;let link=row.querySelector('a');link.href=ALERTS_PAGE;link.textContent='VIEW OFFICIAL ALERTS ↗'}else{box.textContent='Official alert check unavailable. Use the Forest Service alerts link before heading out.'}}
function renderKnown(){if(!inject())return;let p=cachedPos(),row=$('bearKnownRow'),box=$('bearKnownText');row.className='bearIntelRow';if(!p){box.textContent='Location unavailable. Alaska remains bear country; use ADF&G guidance.';return}let miles=hav(p.lat,p.lon,RUSSIAN.lat,RUSSIAN.lon);if(miles<=RUSSIAN.radius){row.className='bearIntelRow known';box.innerHTML=`<strong>${RUSSIAN.name}</strong> · ${miles.toFixed(1)} mi from the reference point. ADF&amp;G says brown and black bears use this area and warns that some bears associate anglers with food and fish.`}else{box.textContent='No special ADF&G bear-awareness area is matched to this GPS position. This does not mean bears are absent.'}}
async function refresh(){renderKnown();if(!navigator.onLine){renderOfficial(cachedAlerts());return}try{let r=await fetch(`${ALERT_URL}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error();let data=await r.json();localStorage.setItem(CACHE,JSON.stringify(data));renderOfficial(data)}catch{renderOfficial(cachedAlerts())}}
function boot(){if(!inject()){setTimeout(boot,250);return}renderKnown();refresh()}
window.addEventListener('online',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});setInterval(refresh,15*60*1000);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
